name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create Release
        id: release
        uses: wgtechlabs/release-build-flow-action@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sync-version-files: true
